name: Periodic health check

on:
  push:
    branches:
      - non-main

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Ping the deployed Pokedex
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-azb0.onrender.com
          max-attempts: 2
          retry-delay: 5s