name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_IN_COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run Jest tests
        run: npm run test
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_IN_COMMIT_MESSAGES != 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify Discord about successful deployment
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ github.event_name == 'push' }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: A new version of Pokedex successfully deployed
          severity: info
      - name: Notify Discord about failed build
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() && github.event_name == 'push' }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: Build failed
          severity: error
          details: commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} broke the build

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SKIP_IN_COMMIT_MESSAGES != 'true' }}
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch